ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true  # Set to `true` if you are working in 2D

    # Frame configurations
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # IMU Configuration
    imu0: "/imu/data"
    imu0_config: [false, false, false,
                  true,  true,  true,
                  false, false, false,
                  false, false, false,
                  true,  true,  true]  # Relevant IMU data to be used by EKF
    imu0_differential: false
    imu0_queue_size: 10

    # GPS Configuration
    odom0: "/odometry/gps"  # This should be the output topic from navsat_transform_node
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_queue_size: 10

    # Optional: Add covariance if needed (can be adjusted to your needs)
    imu0_covariance: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
    odom0_covariance: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
