ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true

    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # IMU topic
    imu0: /imu
    imu0_config: [false, false, false,
                  false, false, false,
                  true,  true,  true,
                  false, false, false,
                  true,  true,  true]
    imu0_differential: false
    imu0_queue_size: 10

    # GPS-converted odometry
    odom0: /odometry/gps
    odom0_config: [true,  true,  false,
                   false, false, false,
                   false, false, false,
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_queue_size: 10
