navsat_transform_node:
  ros__parameters:
    frequency: 20.0  # Match your IMU or GPS publishing rate
    delay: 0.0

    use_odometry_yaw: false  # Don't rely on wheel odometry for heading
    use_local_cartesian: false

    publish_filtered_gps: true
    publish_debug_topics: false
    publish_tf: true

    gps_topic: "/fix"
    imu_topic: "/imu/data"
    odometry_topic: "/odometry/filtered"

    world_frame: "odom"
    base_link_frame: "base_link"
    imu_frame: "imu_link"

    magnetic_declination_radians: 0.0  # Set this if you want magnetic heading corrections
    yaw_offset: 0.0
    zero_altitude: false
    broadcast_utm_transform: false
    broadcast_cartesian_transform: true

    # Use this if your GPS is not at the center of your robot
    # If it's mounted at the robot's center, leave it at 0
    gps_offset_x: 0.0
    gps_offset_y: 0.0
    gps_offset_z: 0.0
