<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_custom_robot_hardware">

  <xacro:property name="chassis_length" value="1.0" /> 
  <xacro:property name="chassis_width"  value="0.58" /> 
  <xacro:property name="chassis_height" value="0.32" /> 
  <xacro:property name="chassis_mass"   value="15.0" /> 
  <xacro:property name="wheel_radius" value="0.14" />

  <xacro:property name="wheel_width"  value="0.12" />
  <xacro:property name="wheel_mass"   value="1.5" />  
  <xacro:property name="wheelbase_x"  value="0.8" />  
  <xacro:property name="track_width"  value="0.55" /> 
  <xacro:property name="wheel_z_offset" value="${-chassis_height + wheel_radius}" /> 
  <xacro:property name="steer_link_length" value="0.02" /> 
  <xacro:property name="steer_link_radius" value="0.01" /> 
  <xacro:property name="steer_link_mass" value="0.1" />   
  <xacro:property name="max_steer_angle" value="${pi/6}" /> 

  <material name="PlasticWhite">
      <color rgba="0.9 0.9 0.9 1.0"/>
  </material>
  <material name="PlasticBlack">
      <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  <material name="PlasticRed">
      <color rgba="0.8 0.1 0.1 1.0"/>
  </material>
  <material name="SensorBlue">
      <color rgba="0.1 0.1 0.8 1.0"/>
  </material>

  <xacro:macro name="box_inertia" params="m l w h">
    <inertia ixx="${m/12 * (h*h + w*w)}" ixy="0.0" ixz="0.0"
             iyy="${m/12 * (h*h + l*l)}" iyz="0.0"
             izz="${m/12 * (w*w + l*l)}" />
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertia ixx="${m/12 * (3*r*r + h*h)}" ixy="0.0" ixz="0.0"
             iyy="${m/12 * (3*r*r + h*h)}" iyz="0.0"
             izz="${m/2 * r*r}" />
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertia ixx="${2*m/5 * r*r}" ixy="0.0" ixz="0.0"
             iyy="${2*m/5 * r*r}" iyz="0.0"
             izz="${2*m/5 * r*r}" />
  </xacro:macro>

  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="PlasticWhite"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/> <mass value="${chassis_mass}"/>
      <xacro:box_inertia m="${chassis_mass}" l="${chassis_length}" w="${chassis_width}" h="${chassis_height}" />
    </inertial>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <xacro:macro name="wheel" params="prefix"> <link name="${prefix}_wheel_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="PlasticBlack"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="${wheel_mass}"/>
        <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}" />
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="${prefix}_steer_link"/> <child link="${prefix}_wheel_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <limit effort="100" velocity="100"/> </joint>

    <transmission name="${prefix}_wheel_transmission">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}_wheel_joint">
         <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${prefix}_wheel_motor">
         <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
         <mechanicalReduction>1</mechanicalReduction> </actuator>
    </transmission>
  </xacro:macro>

  <xacro:macro name="steering_link" params="prefix reflect_steer">
    <link name="${prefix}_steer_link">
      <visual> <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${steer_link_radius}" length="${steer_link_length}"/>
        </geometry>
        <material name="PlasticRed"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${steer_link_radius}" length="${steer_link_length}"/>
        </geometry>
      </collision>
      <inertial> <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${steer_link_mass}"/>
        <xacro:cylinder_inertia m="${steer_link_mass}" r="${steer_link_radius}" h="${steer_link_length}" />
      </inertial>
    </link>

    <joint name="${prefix}_steer_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_steer_link"/>
      <origin xyz="${wheelbase_x/2} ${reflect_steer*track_width/2} ${wheel_z_offset}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/> <limit lower="${-max_steer_angle}" upper="${max_steer_angle}" effort="100" velocity="10"/>
    </joint>

    <transmission name="${prefix}_steer_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="${prefix}_steer_joint">
             <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="${prefix}_steer_motor">
             <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
             <mechanicalReduction>1</mechanicalReduction> </actuator>
    </transmission>

    <xacro:wheel prefix="${prefix}"/>
  </xacro:macro>

  <xacro:macro name="rear_wheel" params="prefix reflect">
      <link name="${prefix}_steer_link"/>
      <joint name="${prefix}_dummy_fixed_joint" type="fixed">
          <parent link="base_link"/>
          <child link="${prefix}_steer_link"/>
          <origin xyz="${-wheelbase_x/2} ${reflect*track_width/2} ${wheel_z_offset}" rpy="0 0 0"/>
      </joint>
      <xacro:wheel prefix="${prefix}"/>
  </xacro:macro>

  <xacro:steering_link prefix="front_left"  reflect_steer="1" />
  <xacro:steering_link prefix="front_right" reflect_steer="-1" />

  <xacro:rear_wheel prefix="rear_left"  reflect="1" />
  <xacro:rear_wheel prefix="rear_right" reflect="-1" />

  <link name="imu_link">
     <visual>
       <geometry>
         <box size="0.05 0.05 0.02"/>
       </geometry>
        <material name="SensorBlue"/>
     </visual>
     <collision>
       <geometry>
         <box size="0.05 0.05 0.02"/>
       </geometry>
     </collision>
     <inertial>
        <mass value="0.05"/> <xacro:box_inertia m="0.05" l="0.05" w="0.05" h="0.02"/>
     </inertial>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.05 0 ${chassis_height/2 - 0.01}" rpy="0 0 0"/>
  </joint>

  <link name="gps_link">
      <visual>
       <geometry>
         <cylinder radius="0.04" length="0.03"/>
       </geometry>
       <material name="SensorBlue"/>
     </visual>
      <collision>
       <geometry>
         <cylinder radius="0.04" length="0.03"/>
       </geometry>
     </collision>
     <inertial>
        <mass value="0.08"/> <xacro:cylinder_inertia m="0.08" r="0.04" h="0.03"/>
     </inertial>
  </link>
  <joint name="gps_joint" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="-0.2 0 ${chassis_height/2 + 0.015}" rpy="0 0 0"/>
  </joint>

  <link name="lidar_link">
     <visual>
       <geometry>
         <cylinder radius="0.05" length="0.07"/>
       </geometry>
       <material name="SensorBlue"/>
     </visual>
     <collision>
       <geometry>
         <cylinder radius="0.05" length="0.07"/>
       </geometry>
     </collision>
      <inertial>
        <mass value="0.2"/> <xacro:cylinder_inertia m="0.2" r="0.05" h="0.07"/>
     </inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${chassis_length/2 - 0.1} 0 ${chassis_height/2 + 0.035}" rpy="0 0 0"/>
  </joint>

  </robot>